### ISSUE TITLE
Exception on initializing database from assset

### ISSUE THREAD

**Issue by nasrabadiAM** [humazed/RoomAsset#2]
Hi
i have a problem to use this library

when i call 
`RoomAsset.databaseBuilder(context.getApplicationContext(), AppDatabase.class, DB_NAME)
                            .build();`

i get this RuntimeError:
` **java.lang.NoClassDefFoundError: Failed resolution of: Lcom/readystatesoftware/sqliteasset/SQLiteAssetHelper**;
                                                                                     at com.huma.room_for_asset.RoomAsset$Companion.openDb(RoomAsset.kt:63)
                                                                                     at com.huma.room_for_asset.RoomAsset$Companion.databaseBuilder(RoomAsset.kt:45)
                                                                                     at com.huma.room_for_asset.RoomAsset$Companion.databaseBuilder$default(RoomAsset.kt:42)
                                                                                     at com.huma.room_for_asset.RoomAsset.databaseBuilder(RoomAsset.kt)
`

**Comment by humazed** [comment]
I updated the library.. please update and tell me if the problem still exists.

Add it in your root build.gradle at the end of repositories:

```gradle
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}
```

Add the dependency
```gradle
dependencies {
    // ... other dependencies
    implementation 'com.github.humazed:RoomAsset:v1.0-beta5'
}
```

**Comment by humazed** [comment]
I'm closing this issue, feel free to open it if the solution didn't solve your problem.
